"""initial_urbanpulse_schema

Revision ID: b6baab1b0fbe
Revises: 
Create Date: 2026-08-30 14:12:45.953580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6baab1b0fbe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence_frames', sa.Column('observation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'evidence_frames', 'observations', ['observation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evidence_frames', type_='foreignkey')
    op.drop_column('evidence_frames', 'observation_id')
    # ### end Alembic commands ###
